### ISSUE TITLE
animes not loading

### ISSUE THREAD

**Issue by skgupta507** [Rahul-Sahani04/V-Anime-App#1]
hello rahul
do i need to add any .env variables for thye websiye to load animes if not could u help with the issue
thanks

**Comment by Rahul-Sahani04** [comment]
Hello,

I regret to inform you that the API I was using to load animes has been shut down. Unfortunately, this means the website won't be able to retrieve the necessary data to display content. If you have an alternative API or source, you might want to consider integrating that into your application.
